### ISSUE TITLE
[DUDE]: Delete on Cascade

### ISSUE THREAD

**Issue by Kikobeats** [balderdashy/waterline-docs#14]
I posted in sails groups but nobody answer me.

It is possbile 'delete on cascade' ? 

https://groups.google.com/forum/#!topic/sailsjs/WBo62pUR_CA

**Comment by mikermcneil** [comment]
Cascading deletes have been implemented in Sails v1 / Waterline 0.13 (see [upgrading guide](https://sailsjs.com/documentation/upgrading/to-v-1-0) for more information)
