### ISSUE TITLE
`and` and `or` in query language can't express certain combinations

### ISSUE THREAD

**Issue by tdanecker** [balderdashy/waterline-docs#141]
Hi,

I have a condition that looks like `(A or B) and (C or D)`. How can I write this using the waterline query language?

The following doesn't work, unfortunatly:
```
model.find({
  or: {
    a: ...,
    b: ...
  },
  or: {
    c: ...,
    d: ...
  }
})
```

**Comment by joezsweet** [comment]
Please post in discuss.erpnext.com, thx

**Comment by particlebanana** [comment]
In the latest beta of Waterline `0.13` this is fully supported syntax:
