### ISSUE TITLE
Question about associations and populate

### ISSUE THREAD

**Issue by Kikobeats** [balderdashy/waterline-docs#16]
I like `populate` but I encounter a scenario when I need it and is not possible.

When you `create` a new model and this model have a association (whatever kind of association) the `create` method return the new object but not return only with the FK of the association. So populate doesn't work when you created news instances.

I fixed it doing a find of the new instance with `populate` and return it, but I'm think that is not efficient.

Is it possible any better solution?

In my particular case, I need that the return contain the model association values (in HTTP and sockets)

My solution:

```
# Create new instance of model using data from params
  Model.create(data).populateAll().exec (err, newInstance) ->

    # Differentiate between waterline-originated validation errors
    # and serious underlying issues. Respond with badRequest if a
    # validation error is encountered, w/ validation info.
    return res.negotiate(err)  if err

    # Use find method to return the model for the populate option
    Model.findOne(newInstance.id).populateAll().exec (err, newInstance) ->

      # If we have the pubsub hook, use the model class's publish method
      # to notify all subscribers about the created item
      if req._sails.hooks.pubsub
        if req.isSocket
          Model.subscribe req, newInstance
          Model.introduce newInstance
        Model.publishCreate newInstance, not req.options.mirror and req

      # Send JSONP-friendly response if it's supported
      # (HTTP 201: Created)

      # Change the id for user.email
      res.status 201
      res.ok newInstance

```

**Comment by devinivy** [comment]
There's a conversation about this and feature request here: https://github.com/balderdashy/waterline/issues/354
