### ISSUE TITLE
Could you add some documentation that describes what the migrate options do?

### ISSUE THREAD

**Issue by BradHarris** [balderdashy/waterline-docs#19]
I couldn't find a mention about migrate anywhere in the docs.

**Comment by devinivy** [comment]
Yup, this is important stuff!

**Comment by dmarcelino** [comment]
There are already some tidbits in [sails-docs: model-settings](https://github.com/balderdashy/sails-docs/blob/master/concepts/ORM/model-settings.md#migrate) and [sails-docs: adapter-specification](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md#auto-migration-strategies).

**Comment by eddieajau** [comment]
Is https://github.com/balderdashy/waterline-docs/blob/master/models/configuration.md#migrate sufficient?

**Comment by dmarcelino** [comment]
`create` seems to be missing (https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md#auto-migration-strategies)
