### ISSUE TITLE
Sails deleted/drops all our collection data in migrate:alter mode

### ISSUE THREAD

**Issue by mahaksib** [balderdashy/waterline-docs#23]
I wanted to understand why migrate:alter is designed in way that it first deletes the collection and then creates the collection and inserts all the previous data in it.

I somehow used migrate:alter in models on our production data and we lost all our data :(. Are there NO ways to recover that lost data?

Could you please explain the exact reason apart from mentioning just use 'migrate:safe' ?

Look forward for an early reply

**Comment by devinivy** [comment]
Closing this and moving over to #19 .
