### ISSUE TITLE
What does the 'alias' of an attribute do?

### ISSUE THREAD

**Issue by micha-LEAP** [balderdashy/waterline-docs#25]
When testing, I noticed that my associations were being given an 'alias' attribute in the schema when using localDisk. Can this be used in the attribute definitions? E.g. my model has a field 'parentID' in the live (SQL)  schema, but I want to refer to the association as 'parent', can I define my attribute with an alias?

Example:
```javascript
// models/Comment.js
module.exports = {
  attributes: {
    ...
    parentId: {
      model: 'comment',
      alias: 'parent'
    },
    ...
  },
  ...
};
```

If not, what is this for?

**Comment by devinivy** [comment]
I don't think that setting this will work, but feel free to try and let us know.  The `alias` attribute property is only use internally to waterline, as far as I know.  It's set here: https://github.com/balderdashy/waterline/blob/master/lib/waterline/core/schema.js#L171
