### ISSUE TITLE
How to find entity using  their associate's attribute?

### ISSUE THREAD

**Issue by hardikbarot** [balderdashy/waterline-docs#27]
Please help me My issue describe as follow 
1) User Entity

var User = Waterline.Collection.extend({

  identity: 'user',
  connection: 'local-postgresql',

  attributes: {
    firstName: 'string',
    lastName: 'string',

    // Add a reference to Pet
    pet: {
      model: 'pet'
    }
  }
});

2) Pet Entity

var Pet = Waterline.Collection.extend({

  identity: 'pet',
  connection: 'local-postgresql',

  attributes: {
    breed: 'string',
    type: 'string',
    name: 'string',

    // Add a reference to User
    user: {
      model: 'user'
    }
  }
});

These entities are associated with each other.
Now I want to find User entity using attribute of pet (i.e name).
How should be query for this situation ?

**Comment by CWyrtzen** [comment]
@hardikbarot has this ever been resolved? Have you brought this question to the Google Group: https://groups.google.com/d/forum/sailsjs?

**Comment by devinivy** [comment]
Hi @hardikbarot–you'll want to do something like this, finding all pets with the name you want to look-up then populating the associated users:
`Pet.find({name: 'Billy'}).populate('user').exec(function(err, pets) {})`

if you have more questions or if this does not work for you, we can reopen this issue.
