### ISSUE TITLE
Document how to create objects without persisting them to the database

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/waterline-docs#35]
Via https://github.com/balderdashy/waterline/issues/763

**Comment by cha0s** [comment]
They said this should work: `new Pet._model(values);` however I think it's smelly and I think we deserve a public API.

**Comment by kevinburke** [comment]
I understand you're frustrated, but saying stuff like "we deserve better" is the kind of thing that leads to open source burnout, and makes people not want to fix the thing you care about. Nobody's paying for this.

**Comment by randallmeeker** [comment]
I think I deserve a pony

**Comment by cha0s** [comment]
I'm sorry if you took it like that. I wasn't trying to demand anything and I think my intent was misunderstood. I should have said that this deserves to be a public API instead.

I of course appreciate the work you're doing :)


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Kevin Burke <notifications@github.com> </div><div>Date:01/16/2015  10:23 AM  (GMT-06:00) </div><div>To: balderdashy/waterline-docs <waterline-docs@noreply.github.com> </div><div>Cc: Ruben Rodriguez <cha0s@therealcha0s.net> </div><div>Subject: Re: [waterline-docs] Document how to create objects without
  persisting them to the database (#35) </div><div>
</div>I understand you're frustrated, but saying stuff like "we deserve better" is the kind of thing that leads to open source burnout, and makes people not want to fix the thing you care about. Nobody's paying for this.

**Comment by cha0s** [comment]
Gonna continue this discussion at balderdashy/waterline#763 where it started

**Comment by devinivy** [comment]
Cool  I'm going to close this out, and we can work on adding documentation once it's part of the public API.

**Comment by cha0s** [comment]
That doesn't set model defaults.
