### ISSUE TITLE
Feature: Default Criteria

### ISSUE THREAD

**Issue by blaketastic2** [balderdashy/waterline-docs#36]
Is there a way to set default criteria on the model? I have a scenario where the legacy database has one table "instances" that have a type. The types can be A and B. Both A and B need to be treated as separate domain objects, and I would like to accomplish this by setting a default criteria on the models as such:

var A = Waterline.Collection.extend({
  attributes: {
    name: 'string',
    ....
  },
  defaultCriteria: {
    type: 'A'
  }
});

var B = Waterline.Collection.extend({
  attributes: {
    name: 'string',
    ....
  },
  defaultCriteria: {
    type: 'B'
  }
});

This would allow us to filter our query by type for all selects, without having to explicitly add the models default criteria on every query.

**Comment by dmarcelino** [comment]
Hi @blaketastic2, a `beforeFind` lifecycle callback (PR balderdashy/waterline#902) is going to be added to waterline v0.11. Would that fix your issue?

BTW, this repo is for waterline documentation, for issues or new feature requests it's best to use the [waterline core repo](https://github.com/balderdashy/waterline).
