### ISSUE TITLE
Many to many through add failed

### ISSUE THREAD

**Issue by thetutlage** [balderdashy/waterline-docs#42]
Whenever i am trying to add `Many to Many through association` it fails with this message.

```bash
/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/associationMethods/add.js:279
var associationKey = collectionAttributes.attributes[attribute.on].via;
TypeError: Cannot read property 'via' of undefined
  at [object Object].Add.createManyToMany (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/lib/associationMethods/add.js:279:69)
```

Here goes my models

### Properties.js
```javascript
module.exports = {
  attributes: {
    id: {
      type: 'integer',
      primaryKey: true,
      autoIncrement: true
    },
    owners:{
      collection: "contacts",
      via: "properties",
      through: 'propertyowners'
    }
  }
};
```

### Contacts.js

```javascript
module.exports = {
  attributes: {
    id: {
      type: 'integer',
      primaryKey: true,
      autoIncrement: true
    },
    username:{
      type:'string',
      unique: true
    },
    properties:{
      collection:"properties",
      via: "owners",
      through: 'propertyowners'
    }
  }
};

```

### PropertyOwners.js

```javascript
module.exports = {
  tableName: 'property_owners',
  tables: ['contacts', 'properties'],
  junctionTable: true,
  attributes: {
     id: {
      primaryKey: true,
      autoIncrement: true,
      type: 'integer'
    },
    properties_ref:{
      columnName: 'property_id',
      type: 'integer',
      foreignKey: true,
      references: 'properties',
      on: 'id',
      via: 'contacts_ref',
      groupBy: 'properties'
    },
    contacts_ref: {
      columnName: 'contact_id',
      type: 'integer',
      foreignKey: true,
      references: 'contacts',
      on: 'id',
      via: 'properties_ref',
      groupBy: 'contacts'
    },
    owner_from_date:{
      type: 'datetime'
    },
    owner_till_date:{
      type: 'datetime'
    },
    is_still_owner:{
      type: 'boolean',
      defaultsTo: true
    }
  }
};
```

No idea what is going wrong

**Comment by thetutlage** [comment]
How frequently you guys check for issues , as i can see a minimum delay for 5 days.

**Comment by CWyrtzen** [comment]
@thetutlage we do our best to move through issues and we also welcome and encourage community input especially from those who may have encountered the same problem. Have you tried asking your question on the Google Group? https://groups.google.com/d/forum/sailsjs

**Comment by dmarcelino** [comment]
Hi @thetutlage, many-to-many through associations are not supported yet, check out **When Many-to-Many Through Associations release** (balderdashy/waterline#705). You may get better responses on that thread since some people there have been hacking with it. Some of us are pushing for a 0.11 release but there hasn't been any new code committed recently...

**Comment by joshbedo** [comment]
Is this still the case? or has Many-to-Many through associations been merged?

**Comment by elennaro** [comment]
I have the same problem with 11

**Comment by AlexVentura** [comment]
I have the same need but I can see it is included yet!
Does anybody have fixed this or maybe another way to bring it working well? Different ways than creating another model as the intermediary table between two models.

**Comment by elennaro** [comment]
@AlexVentura In [tests](https://github.com/balderdashy/waterline/tree/master/test/unit/query/associations) you can find some working examples of Many To Many Through Associations: [Here is the example where add works](https://github.com/balderdashy/waterline/blob/master/test/unit/query/associations/manyToManyThrough.js) and [Here](https://github.com/balderdashy/waterline/blob/master/test/integration/model/toObject.associations.WithForeighKeyTypeDate.js). Take a look at the code.

Also you can show your code example and ask a question on you problem, [here on google groups](https://groups.google.com/forum/#!searchin/sailsjs/waterline), and [here at StackOverflow](http://stackoverflow.com/questions/tagged/waterline).

**Comment by AlexVentura** [comment]
Thanks @elennaro I have followed the first example but it doesn't work for me, maybe I'm doing something wrong but I can make it work. Can you help me out please? This is the [question that I have created at Stackoverflow](http://stackoverflow.com/questions/34570740/how-to-implement-many-to-many-association-using-through-in-sails). I have put the code I'm using now and I hope you could help me out.
Thanks in advance!

**Comment by joshbedo** [comment]
I ended up getting through associations working by using a mediatory table that held the additional columns. After doing this approach though and discussing the trade-offs with my engineering team we decided to remove the join table and store the metadata via a json blob.
