### ISSUE TITLE
Different connections for read and write

### ISSUE THREAD

**Issue by svenvarkel** [balderdashy/waterline-docs#45]
Is it possible to use different connections for replicated MongoDB instances (master and slave)? Is it documented anywhere?

**Comment by CWyrtzen** [comment]
Hi @svenvarkel have you asked your question in the Google Group? https://groups.google.com/d/forum/sailsjs

**Comment by devinivy** [comment]
This is a really good question.  It is possible to use multiple connections, but the behavior is not very sophisticated right now.  See: http://stackoverflow.com/questions/22385823/use-two-different-adapters-in-one-model

Basically, it will merge the adapter methods from both connections into one object.  If you want to separate read and write operations, you can create a custom adapter, or probably manually omit read methods from the adapter on one connection, and manually omit write methods from the adapter on the other connection.  This is getting into uncharted territory, so let us know how it goes if you choose to pursue it!

If you have an idea for how this might work more smoothly, please submit a feature request on the waterline repo.
