### ISSUE TITLE
where query on a Many-to-many association 

### ISSUE THREAD

**Issue by jurajpetrik** [balderdashy/waterline-docs#53]
Let's say I have a many to many association like below.

An user can own many pets and a pet can be owned by many users.
(I changed the table names to user and pet to go in line with the documentation)

    var User = {
      attributes: {
        pets: {
          collection: 'Pet',
          via: 'ownedBy',
          dominant: true
        }
    }

    var Pet = {
      attributes: {
        ownedBy: {
          collection: 'User',
          via: 'pets',
          dominant: true
        }
      }
    };

I want to get all pets owned by a certain user. I tried a query like below. My postgresql db returns an error complaining Pet.ownedBy column doesn't exist. 

    Pet.find()
      .where({
        ownedBy: userId
      })

**Comment by jurajpetrik** [comment]
Solved it.
You can get it like this

    User.findOne({id: userId})
            .populate('pets').
            .exec(function (err, user){
                console.log(user.pets);
          })

**Comment by dmarcelino** [comment]
Good stuff, thanks for sharing @jurajpetrik!
