### ISSUE TITLE
Document model definition option: `ignoreProperties`

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline-docs#66]
`ignoreProperties` are defined in the adapter's `adapter.js` like:

```javascript 
// These properties should be ignored in Waterline validations
validations: {
  ignoreProperties: [ 'async', 'special']
}
```
would allow:
``` javascript
attributes: {
        email: {
          type: 'email',
          special: true
        },
        cousins: {
          collection: 'related',
          via: 'property',
          async: true
        }
}
```
to be accepted by waterline without throwing errors.

Full details on balderdashy/waterline#482.

@mphasize, I stumbled upon `ignoreProperties` (which I had no knowledge of) while doing a code change. Can you possibly write a few words about it in [models.md](https://github.com/balderdashy/waterline-docs/blob/master/models.md)? Thanks! :smiley:

**Comment by mphasize** [comment]
Yep, I guess I should do that. :-)

**Comment by dmarcelino** [comment]
Thanks @mphasize :wink:

**Comment by mphasize** [comment]
@dmarcelino Done, see PR https://github.com/balderdashy/waterline-docs/pull/68

**Comment by dmarcelino** [comment]
Thanks @mphasize!

**Comment by irobert91** [comment]
@mphasize It seems that since it was moved to https://github.com/balderdashy/waterline-docs/blob/master/models/validations.md the configuration part (for `config/models.js`) was lost.
