### ISSUE TITLE
Get objects filtered by values depending on a relationships filter

### ISSUE THREAD

**Issue by washimimizuku** [balderdashy/waterline-docs#76]
Is it possible to make a query where I get records depending on the values of a relationships fields?

For example, this, which doesn't work:
```
{ 
    skip: 0,
    limit: 10,
    sort: 'id asc',
    where: { 
        or: [  
            { 'company.name': { contains: 'Admin' } },
            { name: { contains: 'Gru' } }
         ]
     }
}
```

What I would like to happen is to get all records where company.name contain 'Admin', that is the part I am not being able to do. 

Is there a way to do this? Thanks

**Comment by dmarcelino** [comment]
Hi @washimimizuku, this is not possible (yet). There is an open feature request for this which you can track at balderdashy/waterline#266.

**Comment by washimimizuku** [comment]
Ok, thanks, I'll watch it
