### ISSUE TITLE
how to sepcify the return fields

### ISSUE THREAD

**Issue by kuangyunsheng** [balderdashy/waterline-docs#82]
I want return only the name field  by applying a projection to a waterline query:

Model.find({ where: { age: { '<': 30 } }, select: ['name'] })

but it still return all of the fields。

**Comment by dmarcelino** [comment]
Hi @kuangyunsheng, this github project is only for documentation related issues so this is not the right place to discuss this.

Which adapter are you using? Sails-mongo did not support `select` until recently (balderdashy/sails-mongo#281), a fix has been made and it will go out in the next release (0.11.3 I believe).
