### ISSUE TITLE
Association not cleared in postgresql on the "one" side when destroying the "many" element of a one-to-many association

### ISSUE THREAD

**Issue by tibotiber** [balderdashy/waterline-docs#87]
Hi!
I have a one-to-many association, let say one owner has many pets. When I destroy an owner, the `owner` column of its pets is not cleared in the database. I'm using postgresql. It doesn't really matter in the code since waterline still provides consistent data. But I think it would be better to have the database consistent as well. I'm not sure if this comes from waterline or the postgresql adapter though. 
Any idea or comment?
Thanks,
Thibaut.

**Comment by devinivy** [comment]
Currently when a record is deleted junction table records are removed, but other foreign keys are not.  This feature might not be a bad candidate for 0.11.0.

**Comment by dmarcelino** [comment]
I believe balderdashy/waterline#251 is about the same thing but applied to waterline core.

**Comment by tibotiber** [comment]
@dmarcelino yes it is about the same thing. Sorry my search was not good enough. I guess it's fine closing this then.
