### ISSUE TITLE
Missing findOrCreate and count in Query Methods

### ISSUE THREAD

**Issue by luislobo** [balderdashy/waterline-docs#9]
There are docs for the others but findOrCreate and count are missing

https://github.com/balderdashy/waterline-docs/blob/master/query-methods.md

**Comment by Globegitter** [comment]
About count you can just do ` Model.count().exec(function(err, count) {  });` And I suppose the criteria is so you can filter the count.

**Comment by dmarcelino** [comment]
Thanks @Globegitter!
